//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ap2_Parcial2_Luis_Rodriguez.UI {
    
    
    public partial class rPrestamos {
    }
}
